[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "mongoose"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
